import { useCustomerAuth } from "@/stores/customer-auth";
import { router } from "expo-router";
import { BookingScreen, BookingSection, FormField, OptionalDetails } from "@/components/booking/booking-ui";
import { importSteps } from "@/lib/service-booking";
import { useBookingDraft } from "@/stores/booking-draft";

export default function ImportConsigneeScreen() { const { importDraft, updateImportDraft } = useBookingDraft(); const { customer } = useCustomerAuth(); const supplier = importDraft.supplier ?? { name: "", phone: "" }; const updateSupplier = (field: "name" | "phone" | "company" | "email" | "notes", value: string) => updateImportDraft({ supplier: { ...supplier, [field]: value } }); const selectSupplier = (contact: { name: string; phone: string }) => updateImportDraft({ supplier: { ...supplier, name: contact.name || supplier.name, phone: contact.phone } }); const consignee = importDraft.consignee ?? { name: "", phone: "" }; const update = (field: "name" | "phone", value: string) => updateImportDraft({ consignee: { ...consignee, [field]: value } }); return <BookingScreen activeStep="consignee" serviceLabel="International Imports" progressSteps={importSteps} title="Who will receive the cargo?" detail="Use the person or business responsible for collection or delivery." continueLabel="Review import" continueDisabled={!consignee.name.trim() || !consignee.phone.trim()} onContinue={() => router.push("/import/review" as never)}><BookingSection label={customer && consignee.name === customer.name && consignee.phone === customer.phone ? "Receiver - Me (editable)" : "Receiver"}><FormField label="Receiver name" icon="account-outline" placeholder="Full name or business" value={consignee.name} onContactPicked={(contact) => updateImportDraft({ consignee: { ...consignee, name: contact.name || consignee.name, phone: contact.phone } })} onChangeText={(name) => update("name", name)} /><FormField label="Contact number" icon="phone-outline" placeholder="e.g. +260 97 000 0000" keyboardType="phone-pad" value={consignee.phone} onContactPicked={(contact) => updateImportDraft({ consignee: { ...consignee, name: contact.name || consignee.name, phone: contact.phone } })} onChangeText={(phone) => update("phone", phone)} /></BookingSection><OptionalDetails label="Supplier / Sender Abroad (optional)">
<FormField label="Supplier name" icon="account-outline" placeholder="Contact name" value={supplier.name} onChangeText={(value) => updateSupplier("name", value)} onContactPicked={selectSupplier} />
<FormField label="Supplier phone number" icon="phone-outline" placeholder="Include country code, e.g. +86" keyboardType="phone-pad" value={supplier.phone} onChangeText={(value) => updateSupplier("phone", value)} onContactPicked={selectSupplier} />
<FormField label="Company or business" icon="office-building-outline" placeholder="Company name (optional)" value={supplier.company ?? ""} onChangeText={(value) => updateSupplier("company", value)} />
<FormField label="Supplier email" icon="email-outline" placeholder="Email (optional)" keyboardType="email-address" autoCapitalize="none" value={supplier.email ?? ""} onChangeText={(value) => updateSupplier("email", value)} />
<FormField label="Other contact details" icon="note-text-outline" placeholder="Address or additional contact information (optional)" multiline value={supplier.notes ?? ""} onChangeText={(value) => updateSupplier("notes", value)} />
</OptionalDetails></BookingScreen>; }
