import { useState } from "react";
import { router } from "expo-router";
import { Text, View } from "react-native";

import { BookingQuickEditDrawer } from "@/components/booking/booking-quick-edit-drawer";
import { BookingScreen, SummaryRow } from "@/components/booking/booking-ui";
import { cargoItemsSummary } from "@/lib/booking-cargo";
import { importMethodEditChoices } from "@/lib/booking-review-edits";
import { importSteps, isImportReady } from "@/lib/service-booking";
import { useSubmitBooking } from "@/lib/use-cases/use-submit-booking";
import { useBookingDraft } from "@/stores/booking-draft";

export default function ImportReviewScreen() { const { importDraft, updateImportDraft } = useBookingDraft(); const submission = useSubmitBooking(); const [methodEditOpen, setMethodEditOpen] = useState(false); const submit = async () => { const result = await submission.submit("import", importDraft); if (result) router.replace({ pathname: "/import/confirmation", params: { shipmentId: result.id, reference: result.reference } } as never); }; return <BookingScreen activeStep="review" serviceLabel="International Imports" progressSteps={importSteps} title="Review your import" detail="This starts an import request. Your final quote is confirmed after review." continueLabel={submission.status === "submitting" ? "Submitting..." : "Request import quote"} continueDisabled={!isImportReady(importDraft) || submission.status === "submitting"} onContinue={submit}><View><SummaryRow label="Method" value={importDraft.method === "air" ? "Air Freight" : "Sea Freight"} onEdit={() => setMethodEditOpen(true)} /><SummaryRow label="Route" value={`${importDraft.originCity ?? "Origin"}, ${importDraft.originCountry ?? ""} → ${importDraft.destinationCity ?? "Destination"}`} /><SummaryRow label="Cargo" value={cargoItemsSummary(importDraft.cargoItems, importDraft.cargoDescription || importDraft.cargoCategory || "Not selected")} /><SummaryRow label="Photos" value={importDraft.cargoPhotos?.length ? `${importDraft.cargoPhotos.length} added` : "None"} /><SummaryRow label="Supplier document" value={importDraft.supportingDocument?.name ?? "Not attached"} /><SummaryRow label="Consignee" value={importDraft.consignee?.name ?? "Not provided"} /></View>{submission.errorMessage ? <Text style={{ color: "#B42318", fontSize: 12, fontWeight: "700" }}>{submission.errorMessage}</Text> : null}<BookingQuickEditDrawer<"air" | "sea"> visible={methodEditOpen} overline="Import method" title="Change freight method" detail="Change this preference without leaving your review." value={(importDraft.method ?? "air") as "air" | "sea"} choices={importMethodEditChoices} approveLabel="Update method" onDismiss={() => setMethodEditOpen(false)} onApprove={(method) => { updateImportDraft({ method }); setMethodEditOpen(false); }} /></BookingScreen>; }
