import type { PropsWithChildren, ReactNode } from "react";
import { KeyboardAvoidingView, Modal, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { AppIcon, type AppIconName } from "@/components/ui/app-icon";
import { PrimaryButton, SecondaryButton } from "@/components/ui/nwc-ui";
import { nwcColors } from "@/lib/nwc-theme";

type FullScreenFormDrawerProps = PropsWithChildren<{ visible: boolean; overline: string; title: string; detail: string; approveLabel: string; approveIcon?: AppIconName; approveDisabled?: boolean; onApprove: () => void; onDismiss: () => void; footerNote?: ReactNode }>;

export function FullScreenFormDrawer({ visible, overline, title, detail, approveLabel, approveIcon = "check", approveDisabled, onApprove, onDismiss, footerNote, children }: FullScreenFormDrawerProps) {
  const insets = useSafeAreaInsets();
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onDismiss} statusBarTranslucent><View style={styles.backdrop}><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Close ${title}`} onPress={onDismiss} style={styles.dismiss} /><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.keyboard}><View accessibilityViewIsModal style={styles.drawer}><View style={styles.grabber} /><View style={styles.header}><View style={styles.headerCopy}><Text style={styles.overline}>{overline}</Text><Text style={styles.title}>{title}</Text><Text style={styles.detail}>{detail}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Close ${title}`} onPress={onDismiss} style={styles.close}><AppIcon name="close" size={21} color={nwcColors.brandNavy} /></TouchableOpacity></View><ScrollView keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled" contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>{children}</ScrollView><View style={[styles.footer, { paddingBottom: Math.max(insets.bottom, 16) }]}>{footerNote ? <View style={styles.footerNote}>{footerNote}</View> : null}<View style={styles.actions}><SecondaryButton label="Cancel" onPress={onDismiss} style={styles.action} /><PrimaryButton label={approveLabel} icon={approveIcon} disabled={approveDisabled} onPress={onApprove} style={styles.action} /></View></View></View></KeyboardAvoidingView></View></Modal>;
}

const styles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(1,38,66,0.36)" }, dismiss: { ...StyleSheet.absoluteFillObject }, keyboard: { flex: 1, justifyContent: "flex-end" }, drawer: { flex: 1, marginTop: 52, overflow: "hidden", borderTopLeftRadius: 31, borderTopRightRadius: 31, backgroundColor: nwcColors.background }, grabber: { alignSelf: "center", width: 44, height: 5, borderRadius: 3, marginTop: 11, backgroundColor: "#C8D3D8" }, header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 15, flexDirection: "row", gap: 12, alignItems: "flex-start", borderBottomWidth: 1, borderBottomColor: "#E6ECEE" }, headerCopy: { flex: 1, gap: 2 }, overline: { color: nwcColors.info, fontSize: 10, lineHeight: 14, letterSpacing: 0.75, textTransform: "uppercase", fontFamily: "Poppins_800ExtraBold" }, title: { color: nwcColors.foreground, fontSize: 24, lineHeight: 30, fontFamily: "Poppins_800ExtraBold" }, detail: { color: nwcColors.muted, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_500Medium" }, close: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.surfaceRaised }, body: { gap: 12, padding: 20, paddingBottom: 28 }, footer: { borderTopWidth: 1, borderTopColor: "#E4EAEC", paddingHorizontal: 20, paddingTop: 12, gap: 9, backgroundColor: nwcColors.surfaceElevated }, footerNote: { alignItems: "center" }, actions: { flexDirection: "row", gap: 9 }, action: { flex: 1 },
});
