import { useEffect, useMemo, useState } from "react";
import { KeyboardAvoidingView, Modal, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { CustomerMap } from "@/components/map/customer-map";
import { AppIcon } from "@/components/ui/app-icon";
import { PrimaryButton, SecondaryButton } from "@/components/ui/nwc-ui";
import type { MockDirectoryItem } from "@/lib/mock-account-directory";
import { routeSuggestionToAddress, searchRouteSuggestions, type RouteSuggestion } from "@/lib/route-autocomplete";
import { nwcColors } from "@/lib/nwc-theme";

type LocationFinderDrawerProps = { visible: boolean; item: MockDirectoryItem | null; onDismiss: () => void; onSave: (item: { id?: string; label: string; detail: string }) => void };

export function LocationFinderDrawer({ visible, item, onDismiss, onSave }: LocationFinderDrawerProps) {
  const [label, setLabel] = useState("");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<RouteSuggestion | null>(null);
  useEffect(() => { if (visible) { setLabel(item?.label ?? ""); setQuery(item?.detail ?? ""); setSelected(null); } }, [item, visible]);
  const suggestions = useMemo(() => searchRouteSuggestions("local", query), [query]);
  const selectedAddress = selected ? routeSuggestionToAddress(selected) : undefined;
  const save = () => { if (!label.trim() || !query.trim()) return; onSave({ id: item?.id || undefined, label: label.trim(), detail: selected?.label ?? query.trim() }); };
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onDismiss} statusBarTranslucent><View style={styles.backdrop}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Close saved place editor" onPress={onDismiss} style={styles.dismiss} /><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.keyboard}><View accessibilityViewIsModal style={styles.sheet}><View style={styles.grabber} /><View style={styles.heading}><View style={styles.headingCopy}><Text style={styles.overline}>Saved place</Text><Text style={styles.title}>{item?.id ? "Edit saved place" : "Find a place"}</Text><Text style={styles.detail}>Search nearby locations, inspect the mock map, then save a name you will recognize.</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Close saved place editor" onPress={onDismiss} style={styles.close}><AppIcon name="close" size={20} color={nwcColors.brandNavy} /></TouchableOpacity></View><CustomerMap mode="location-picker" destination={selectedAddress} height={144} style={styles.map} /><View style={styles.form}><TextInput accessibilityLabel="Saved place name" value={label} onChangeText={setLabel} placeholder="Place name, e.g. Home" placeholderTextColor="#91A0AE" returnKeyType="next" style={styles.input} /><View style={styles.search}><AppIcon name="magnify" size={19} color={nwcColors.info} /><TextInput accessibilityLabel="Find a nearby location" value={query} onChangeText={(value) => { setQuery(value); setSelected(null); }} placeholder="Find a nearby location" placeholderTextColor="#91A0AE" returnKeyType="search" style={styles.searchInput} /></View><View style={styles.results}>{suggestions.map((suggestion) => <TouchableOpacity key={suggestion.id} accessibilityRole="button" accessibilityState={{ selected: selected?.id === suggestion.id }} accessibilityLabel={`Use ${suggestion.label}`} onPress={() => { setSelected(suggestion); setQuery(suggestion.label); }} style={[styles.result, selected?.id === suggestion.id && styles.resultSelected]}><View style={styles.resultIcon}><AppIcon name={suggestion.kind === "branch" ? "warehouse" : "map-marker-outline"} size={18} color={nwcColors.brandNavy} /></View><View style={styles.resultCopy}><Text numberOfLines={1} style={styles.resultTitle}>{suggestion.label}</Text><Text numberOfLines={1} style={styles.resultDetail}>{suggestion.detail}</Text></View>{selected?.id === suggestion.id ? <AppIcon name="check-circle" size={19} color={nwcColors.success} /> : null}</TouchableOpacity>)}</View><View style={styles.actions}><SecondaryButton label="Cancel" onPress={onDismiss} /><PrimaryButton label="Save place" icon="check" disabled={!label.trim() || !query.trim()} onPress={save} /></View></View></View></KeyboardAvoidingView></View></Modal>;
}

const styles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(1,38,66,0.35)" }, dismiss: { ...StyleSheet.absoluteFillObject }, keyboard: { width: "100%" }, sheet: { maxHeight: "91%", borderTopLeftRadius: 30, borderTopRightRadius: 30, overflow: "hidden", paddingHorizontal: 20, paddingBottom: Platform.OS === "ios" ? 28 : 20, backgroundColor: nwcColors.background, gap: 13 }, grabber: { alignSelf: "center", width: 42, height: 5, borderRadius: 3, marginTop: 10, backgroundColor: "#C7D2D7" }, heading: { flexDirection: "row", gap: 12, alignItems: "flex-start" }, headingCopy: { flex: 1, gap: 2 }, overline: { color: nwcColors.info, fontSize: 10, lineHeight: 14, letterSpacing: 0.75, textTransform: "uppercase", fontFamily: "Poppins_800ExtraBold" }, title: { color: nwcColors.foreground, fontSize: 23, lineHeight: 29, fontFamily: "Poppins_800ExtraBold" }, detail: { color: nwcColors.muted, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_500Medium" }, close: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.surfaceRaised }, map: { borderRadius: 20 }, form: { gap: 9 }, input: { minHeight: 47, paddingHorizontal: 13, borderRadius: 15, borderWidth: 1, borderColor: "#DCE6E8", backgroundColor: nwcColors.surfaceElevated, color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_600SemiBold" }, search: { minHeight: 49, paddingHorizontal: 13, borderRadius: 15, borderWidth: 1, borderColor: "#DCE6E8", backgroundColor: nwcColors.surfaceElevated, flexDirection: "row", alignItems: "center", gap: 8 }, searchInput: { flex: 1, color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_600SemiBold" }, results: { gap: 6, maxHeight: 162 }, result: { minHeight: 53, paddingHorizontal: 9, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: nwcColors.surface }, resultSelected: { borderWidth: 1, borderColor: nwcColors.primary, backgroundColor: nwcColors.surfaceAccent }, resultIcon: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.surfaceNavyTint }, resultCopy: { flex: 1, gap: 1 }, resultTitle: { color: nwcColors.foreground, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_800ExtraBold" }, resultDetail: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_500Medium" }, actions: { flexDirection: "row", gap: 9, marginTop: 2 },
});
