import { Skeleton, SkeletonGroup } from "@/components/ui/skeleton";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppIcon } from "@/components/ui/app-icon";
import { nwcColors } from "@/lib/nwc-theme";
import { cargoItemsSummary } from "@/lib/booking-cargo";
import type { ImportBookingDraft, IntercityBookingDraft, LocalDeliveryDraft, BookingQuote } from "@/types/cargo";

type Draft = ImportBookingDraft | IntercityBookingDraft | LocalDeliveryDraft;
export function ShipmentTicket({ draft, reference, status = "Review booking", onEditRoute, onEditContacts, onEditCargo }: { draft: Draft; reference?: string; status?: string; onEditRoute?: () => void; onEditContacts?: () => void; onEditCargo?: () => void }) {
  const local = draft.service === "local";
  const international = draft.service === "import";
  const origin = local ? draft.pickup?.detail : [draft.originCity, international ? draft.originCountry : ""].filter(Boolean).join(", ");
  const destination = local ? draft.destination?.detail : draft.destinationCity;
  const sender = international ? draft.supplier : draft.sender;
  const receiver = international ? draft.consignee : draft.receiver;
  const items = draft.cargoItems ?? [];
  const quantity = items.reduce((total, item) => total + item.quantity, 0);
  const weight = items.length && items.every((item) => item.weight != null) ? items.reduce((total, item) => total + item.weight! * item.quantity, 0) : undefined;
  return <View style={styles.ticket}>
    <View style={styles.top}><View style={styles.brand}><AppIcon name="package-variant-closed" size={26} color={nwcColors.primary} /><Text style={styles.brandName}>NEW WORLD CARGO</Text></View><Text style={styles.service}>{local ? "Local delivery" : international ? "International shipment" : "City-to-City"}</Text></View>
    <View style={styles.body}><View style={styles.referenceRow}><View style={{ flex: 1 }}><Text style={styles.label}>{reference ? "Shipment reference" : "Shipment summary"}</Text><Text selectable style={styles.reference}>{reference || "Booking preview"}</Text></View><View style={styles.chip}><Text style={styles.chipText}>{status}</Text></View></View>
    <TouchableOpacity disabled={!onEditRoute} onPress={onEditRoute} accessibilityRole={onEditRoute ? "button" : undefined} accessibilityLabel="Edit shipment route" style={styles.route}>
      <View style={styles.routeMarks}><View style={styles.dot} /><View style={styles.line} /><AppIcon name="map-marker" size={22} color={nwcColors.primary} /></View><View style={{ flex: 1, gap: 20 }}><View><Text style={styles.label}>From</Text><Text style={styles.place}>{origin || "Add pickup"}</Text></View><View><Text style={styles.label}>To</Text><Text style={styles.place}>{destination || "Add destination"}</Text></View></View>{onEditRoute ? <AppIcon name="pencil-outline" size={18} color={nwcColors.primary} /> : null}
    </TouchableOpacity>
    <View style={styles.perforation} />
    <TouchableOpacity disabled={!onEditContacts} onPress={onEditContacts} accessibilityRole={onEditContacts ? "button" : undefined} accessibilityLabel="Edit sender and receiver" style={styles.contacts}><View style={styles.contact}><Text style={styles.label}>{international ? "Supplier / Sender" : "Sender"}</Text><Text style={styles.value}>{sender?.name || (international ? "Not provided (optional)" : "Add sender")}</Text>{sender?.phone ? <Text style={styles.phone}>{sender.phone}</Text> : null}</View><View style={styles.contact}><Text style={styles.label}>Receiver</Text><Text style={styles.value}>{receiver?.name || "Add receiver"}</Text>{receiver?.phone ? <Text style={styles.phone}>{receiver.phone}</Text> : null}</View>{onEditContacts ? <AppIcon name="pencil-outline" size={16} color={nwcColors.primary} /> : null}</TouchableOpacity>
    {international && draft.supplier && (draft.supplier.company || draft.supplier.email || draft.supplier.notes) ? <View style={{ gap: 4 }}><Text style={styles.label}>Supplier details</Text><Text style={styles.phone}>{[draft.supplier.company, draft.supplier.email, draft.supplier.notes].filter(Boolean).join(" / ")}</Text></View> : null}
    {draft.supportingDocument || draft.cargoPhotos?.length ? <View style={{ gap: 4 }}><Text style={styles.label}>Attachments</Text><Text style={styles.phone}>{[draft.supportingDocument?.name, draft.cargoPhotos?.length ? draft.cargoPhotos.length + " photos" : undefined].filter(Boolean).join(" / ")}</Text></View> : null}
    </View><TouchableOpacity disabled={!onEditCargo} onPress={onEditCargo} accessibilityRole={onEditCargo ? "button" : undefined} accessibilityLabel="Edit cargo" style={styles.cargo}><AppIcon name="package-variant" size={23} color={nwcColors.brandNavy} /><View style={{ flex: 1 }}><Text style={styles.cargoTitle}>{cargoItemsSummary(items, "Add package details")}</Text><Text style={styles.cargoMeta}>{[quantity ? `${quantity} item${quantity === 1 ? "" : "s"}` : undefined, weight != null ? `${weight} kg` : undefined].filter(Boolean).join(" / ")}</Text></View>{onEditCargo ? <AppIcon name="pencil-outline" size={18} color={nwcColors.brandNavy} /> : null}</TouchableOpacity>
  </View>;
}
export function ShipmentCharges({ quote, loading, error }: { quote?: BookingQuote; loading?: boolean; error?: string }) {
  if (loading) return <View style={styles.charges}><Text style={styles.chargesTitle}>Price summary</Text><SkeletonGroup label="Loading quote"><Skeleton style={{height:28, width:"70%"}} /><Skeleton style={{height:16, width:"90%"}} /></SkeletonGroup></View>;
  return <View style={styles.charges}><Text style={styles.chargesTitle}>Price summary</Text><View style={styles.totalRow}><Text style={styles.totalLabel}>Estimated total</Text><Text style={styles.total}>{loading ? "Updating..." : error ? "Unavailable" : quote?.source === "server" ? quote.formattedTotal : "Quote pending"}</Text></View>{quote?.source === "server" && !loading && !error ? <Text style={styles.note}>{quote.currency} · Review the quoted amount before confirming.</Text> : <Text accessibilityRole={error ? "alert" : undefined} style={styles.note}>{error || "Charges will be confirmed with your quote."}</Text>}</View>;
}
const styles = StyleSheet.create({ ticket: { backgroundColor: nwcColors.brandNavy, borderRadius: 24, overflow: "hidden" }, top: { padding: 20, borderBottomWidth: 1, borderBottomColor: "#365366", gap: 8 }, brand: { flexDirection: "row", gap: 10, alignItems: "center" }, brandName: { color: "white", fontFamily: "Poppins_700Bold", fontSize: 15, letterSpacing: 0.6 }, service: { color: nwcColors.primary, fontFamily: "Poppins_500Medium", fontSize: 13 }, body: { padding: 20, gap: 24 }, referenceRow: { gap: 10 }, reference: { color: "white", fontSize: 21, fontFamily: "Poppins_700Bold", marginTop: 5 }, chip: { alignSelf: "flex-start", borderRadius: 20, backgroundColor: "#294757", paddingHorizontal: 10, paddingVertical: 5 }, chipText: { color: nwcColors.primary, fontSize: 11, fontFamily: "Poppins_600SemiBold" }, label: { color: "#BCD0DA", fontSize: 11, fontFamily: "Poppins_500Medium" }, route: { flexDirection: "row", gap: 12 }, routeMarks: { alignItems: "center", paddingTop: 7, paddingBottom: 4 }, dot: { width: 12, height: 12, borderWidth: 3, borderColor: nwcColors.primary, borderRadius: 8 }, line: { flex: 1, borderLeftWidth: 2, borderColor: "#8B823F", minHeight: 30, marginVertical: 5 }, place: { color: "white", fontSize: 19, lineHeight: 27, fontFamily: "Poppins_600SemiBold" }, perforation: { borderTopWidth: 1, borderStyle: "dashed", borderColor: "#617788" }, contacts: { flexDirection: "row", gap: 14 }, contact: { flex: 1, gap: 4 }, value: { color: "white", fontSize: 14, fontFamily: "Poppins_600SemiBold" }, phone: { color: "#D8E3E8", fontSize: 12 }, cargo: { flexDirection: "row", gap: 12, alignItems: "center", padding: 20, backgroundColor: nwcColors.primary }, cargoTitle: { color: nwcColors.brandNavy, fontSize: 15, fontFamily: "Poppins_600SemiBold" }, cargoMeta: { color: nwcColors.brandNavy, fontSize: 12, marginTop: 3 }, charges: { padding: 18, borderWidth: 1, borderColor: nwcColors.border, borderRadius: 20, gap: 14 }, chargesTitle: { fontSize: 16, color: nwcColors.foreground, fontFamily: "Poppins_600SemiBold" }, totalRow: { flexDirection: "row", flexWrap: "wrap", gap: 12, justifyContent: "space-between", alignItems: "center" }, totalLabel: { fontSize: 14, color: nwcColors.muted }, total: { fontSize: 24, color: nwcColors.brandNavy, fontFamily: "Poppins_700Bold" }, note: { fontSize: 12, lineHeight: 18, color: nwcColors.muted } });
