import { ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";

import { AppIcon } from "@/components/ui/app-icon";
import { IconButton, PrimaryButton, Screen, StatusBadge } from "@/components/ui/nwc-ui";
import { nwcColors } from "@/lib/nwc-theme";

const services = [
  { title: "Local Delivery", detail: "Within your city, with a route-first booking flow." },
  { title: "City-to-City", detail: "Cargo movement between Zambia’s cities and service points." },
  { title: "International Imports", detail: "Air and sea import requests with customer tracking." },
  { title: "Custom Request", detail: "A tailored cargo plan when a standard service is not enough." },
];

export default function AboutNewWorldCargoScreen() {
  return <Screen><View style={styles.page}><View style={styles.header}><IconButton label="Go back" icon="arrow-left" onPress={() => router.back()} /><Text style={styles.headerTitle}>About</Text><View style={styles.headerSpacer} /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.heroIcon}><AppIcon name="package-variant-closed" size={29} color={nwcColors.primaryInk} /></View><Text style={styles.eyebrow}>New WorldCargo</Text><Text style={styles.title}>Move cargo with confidence.</Text><Text style={styles.detail}>Book delivery, follow cargo, manage records, and get help from one customer app.</Text><StatusBadge label="Customer app preview" tone="info" icon="information-outline" /></View><View style={styles.section}><Text style={styles.sectionTitle}>What you can book</Text><View style={styles.services}>{services.map((service) => <View key={service.title} style={styles.serviceRow}><View style={styles.serviceDot} /><View style={styles.serviceCopy}><Text style={styles.serviceTitle}>{service.title}</Text><Text style={styles.serviceDetail}>{service.detail}</Text></View></View>)}</View></View><View style={styles.support}><AppIcon name="headset" size={21} color={nwcColors.brandNavy} /><View style={styles.supportCopy}><Text style={styles.supportTitle}>Customer support in the app</Text><Text style={styles.supportDetail}>Open Support for cargo questions, payment records, or account help. Add evidence to a case when it is useful.</Text></View></View></ScrollView><View style={styles.footer}><PrimaryButton label="Open Support" icon="headset" onPress={() => router.push("/support" as never)} /></View></View></Screen>;
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: nwcColors.background }, header: { minHeight: 60, paddingHorizontal: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { flex: 1, textAlign: "center", color: nwcColors.brandNavy, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, headerSpacer: { height: 44, width: 44 }, content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 124, gap: 26 }, hero: { alignItems: "center", gap: 7, paddingTop: 9 }, heroIcon: { width: 67, height: 67, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.primary }, eyebrow: { color: nwcColors.info, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_800ExtraBold", letterSpacing: 0.9, textTransform: "uppercase", marginTop: 7 }, title: { color: nwcColors.foreground, fontSize: 29, lineHeight: 37, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.5, textAlign: "center" }, detail: { color: nwcColors.muted, fontSize: 13, lineHeight: 19, fontFamily: "Poppins_500Medium", textAlign: "center" }, section: { gap: 9 }, sectionTitle: { color: nwcColors.foreground, fontSize: 17, lineHeight: 23, fontFamily: "Poppins_800ExtraBold" }, services: { borderRadius: 24, paddingHorizontal: 15, borderWidth: 1, borderColor: "#E2EAEC", backgroundColor: nwcColors.surface }, serviceRow: { minHeight: 71, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: nwcColors.border }, serviceDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: nwcColors.primary }, serviceCopy: { flex: 1, gap: 1 }, serviceTitle: { color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" }, serviceDetail: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, support: { padding: 15, borderRadius: 21, flexDirection: "row", alignItems: "flex-start", gap: 11, backgroundColor: "#EEF5F7" }, supportCopy: { flex: 1, gap: 2 }, supportTitle: { color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, supportDetail: { color: nwcColors.info, fontSize: 11, lineHeight: 17, fontFamily: "Poppins_500Medium" }, footer: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 20, borderTopWidth: 1, borderTopColor: "#E6ECEE", backgroundColor: nwcColors.background },
});
