import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { AppIcon } from "@/components/ui/app-icon";
import { Card, IconButton, PrimaryButton, Screen, SecondaryButton, StatusBadge } from "@/components/ui/nwc-ui";
import { paymentMethodIcon } from "@/lib/mock-billing";
import { nwcColors } from "@/lib/nwc-theme";
import { useMockBilling } from "@/stores/mock-billing";

export default function PaymentMethodsScreen() {
  const { paymentMethods, selectedPaymentMethodId, selectSavedPaymentMethod, setDefaultPaymentMethod, addMockPaymentMethod, removeMockPaymentMethod } = useMockBilling();
  const openAddMethod = () => Alert.alert("Add a payment method", "Choose a mock payment type for this frontend preview.", [{ text: "Mobile money", onPress: () => addMockPaymentMethod("mobile") }, { text: "Bank card", onPress: () => addMockPaymentMethod("card") }, { text: "Cancel", style: "cancel" }]);
  const remove = (id: string, label: string) => { if (id === "wallet") { Alert.alert("Cargo Wallet", "Your assigned Cargo Wallet remains available in this preview."); return; } removeMockPaymentMethod(id); };
  return <Screen><View style={styles.page}><View style={styles.header}><IconButton label="Go back" icon="arrow-left" onPress={() => router.back()} /><Text style={styles.headerTitle}>Payment methods</Text><View style={styles.headerSpacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.titleBlock}><Text style={styles.title}>Pay your way</Text><Text style={styles.detail}>Choose a default method for bills. These details are mock data and no payment account is connected.</Text></View><View style={styles.methods}>{paymentMethods.map((item) => <TouchableOpacity key={item.id} accessibilityRole="radio" accessibilityState={{ selected: item.id === selectedPaymentMethodId }} accessibilityLabel={`Use ${item.label}`} onPress={() => selectSavedPaymentMethod(item.id)} activeOpacity={0.74} style={[styles.method, item.id === selectedPaymentMethodId && styles.methodSelected]}><View style={[styles.methodIcon, item.method === "wallet" && styles.walletIcon]}><AppIcon name={paymentMethodIcon(item.method)} size={21} color={nwcColors.primaryInk} /></View><View style={styles.methodCopy}><View style={styles.methodTitleLine}><Text style={styles.methodTitle}>{item.label}</Text>{item.isDefault ? <StatusBadge label="Default" tone="success" /> : null}</View><Text style={styles.methodDetail}>{item.detail}</Text></View><View style={[styles.radio, item.id === selectedPaymentMethodId && styles.radioSelected]}>{item.id === selectedPaymentMethodId ? <View style={styles.radioDot} /> : null}</View><View style={styles.methodActions}><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Make ${item.label} default`} onPress={() => setDefaultPaymentMethod(item.id)} style={styles.textAction}><Text style={styles.textActionLabel}>Default</Text></TouchableOpacity>{item.method !== "wallet" ? <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Remove ${item.label}`} onPress={() => remove(item.id, item.label)} style={styles.textAction}><Text style={styles.removeLabel}>Remove</Text></TouchableOpacity> : null}</View></TouchableOpacity>)}</View><Card style={styles.walletNote}><AppIcon name="wallet-outline" size={20} color={nwcColors.brandNavy} /><View style={styles.walletCopy}><Text style={styles.walletTitle}>Cargo Wallet</Text><Text style={styles.walletDetail}>Every customer has a wallet. Add mock balance from Bills whenever you need it.</Text></View></Card><View style={styles.actions}><PrimaryButton label="Add payment method" icon="plus" onPress={openAddMethod} /><SecondaryButton label="Done" onPress={() => router.back()} /></View></ScrollView></View></Screen>;
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: nwcColors.background, paddingHorizontal: 20, paddingTop: 16 }, header: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { color: nwcColors.brandNavy, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" }, headerSpacer: { width: 44, height: 44 }, content: { paddingTop: 24, paddingBottom: 42, gap: 18 }, titleBlock: { gap: 4 }, title: { color: nwcColors.foreground, fontSize: 29, lineHeight: 37, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.5 }, detail: { color: nwcColors.muted, fontSize: 13, lineHeight: 19, fontFamily: "Poppins_500Medium" }, methods: { gap: 10 }, method: { minHeight: 91, borderRadius: 22, padding: 12, flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 10, backgroundColor: nwcColors.surface, borderWidth: 1, borderColor: "#E0E8EA" }, methodSelected: { backgroundColor: "#F2F8FA", borderColor: nwcColors.brandNavy }, methodIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#EAF1F4" }, walletIcon: { backgroundColor: nwcColors.primary }, methodCopy: { minWidth: 0, flex: 1, gap: 2 }, methodTitleLine: { flexDirection: "row", alignItems: "center", gap: 6 }, methodTitle: { color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, methodDetail: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1.5, borderColor: nwcColors.border, alignItems: "center", justifyContent: "center" }, radioSelected: { borderColor: nwcColors.brandNavy }, radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: nwcColors.brandNavy }, methodActions: { width: "100%", marginLeft: 52, flexDirection: "row", gap: 15 }, textAction: { minHeight: 28, justifyContent: "center" }, textActionLabel: { color: nwcColors.info, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_800ExtraBold" }, removeLabel: { color: nwcColors.error, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_800ExtraBold" }, walletNote: { flexDirection: "row", gap: 10, backgroundColor: "#F1F7F8" }, walletCopy: { flex: 1, gap: 2 }, walletTitle: { color: nwcColors.brandNavy, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" }, walletDetail: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, actions: { gap: 10 },
});
