import { useState } from "react";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router } from "expo-router";
import { AppIcon } from "@/components/ui/app-icon";
import { Card, IconButton, PrimaryButton, SecondaryButton, Screen } from "@/components/ui/nwc-ui";
import { nwcColors } from "@/lib/nwc-theme";
import { useCustomerAuth } from "@/stores/customer-auth";

export default function AccountRecoveryScreen() {
  const { customer } = useCustomerAuth();
  const [codeVisible, setCodeVisible] = useState(false);
  const [sessionsCleared, setSessionsCleared] = useState(false);
  return <Screen><View style={styles.page}><View style={styles.header}><IconButton label="Go back" icon="arrow-left" onPress={() => router.back()} /><Text style={styles.headerTitle}>Account recovery</Text><View style={styles.headerSpacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.titleBlock}><Text style={styles.title}>Keep access secure</Text><Text style={styles.detail}>Your verified phone is used to restore access. These controls are frontend mock states only.</Text></View><Card style={styles.phone}><View style={styles.phoneIcon}><AppIcon name="cellphone" size={21} color={nwcColors.primaryInk} /></View><View style={styles.phoneCopy}><Text style={styles.phoneLabel}>Verified phone</Text><Text style={styles.phoneValue}>{customer?.phone ?? "+260 97••• 0187"}</Text></View></Card><Card style={styles.recoveryCard}><Text style={styles.cardTitle}>Recovery code</Text><Text style={styles.cardDetail}>Keep this code offline. It can help you recover access if you change your phone.</Text>{codeVisible ? <View style={styles.code}><Text style={styles.codeText}>NWC-4K8P-92QX</Text></View> : null}<TouchableOpacity accessibilityRole="button" accessibilityLabel={codeVisible ? "Hide recovery code" : "Show mock recovery code"} onPress={() => setCodeVisible((visible) => !visible)} style={styles.inlineAction}><Text style={styles.inlineActionText}>{codeVisible ? "Hide code" : "Show code"}</Text></TouchableOpacity></Card><Card style={styles.recoveryCard}><Text style={styles.cardTitle}>Other devices</Text><Text style={styles.cardDetail}>{sessionsCleared ? "Other mock sessions were signed out." : "Sign out on another device if you think your account is at risk."}</Text>{sessionsCleared ? <View style={styles.confirmed}><AppIcon name="check" size={15} color={nwcColors.success} /><Text style={styles.confirmedText}>Other sessions cleared</Text></View> : <TouchableOpacity accessibilityRole="button" accessibilityLabel="Sign out other mock sessions" onPress={() => setSessionsCleared(true)} style={styles.inlineAction}><Text style={styles.inlineActionText}>Sign out other devices</Text></TouchableOpacity>}</Card><View style={styles.actions}><PrimaryButton label="Continue with phone" icon="cellphone" onPress={() => router.push("/auth/phone")} /><SecondaryButton label="Contact support" onPress={() => router.push("/support")} /></View></ScrollView></View></Screen>;
}

const styles = StyleSheet.create({
  page: { flex: 1, paddingTop: 16, paddingHorizontal: 20, backgroundColor: nwcColors.background }, header: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { color: nwcColors.brandNavy, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" }, headerSpacer: { width: 44, height: 44 }, content: { paddingTop: 24, paddingBottom: 42, gap: 16 }, titleBlock: { gap: 4 }, title: { color: nwcColors.foreground, fontSize: 29, lineHeight: 37, letterSpacing: -0.5, fontFamily: "Poppins_800ExtraBold" }, detail: { color: nwcColors.muted, fontSize: 13, lineHeight: 19, fontFamily: "Poppins_500Medium" }, phone: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#F2F8FA" }, phoneIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.primary }, phoneCopy: { gap: 1 }, phoneLabel: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" }, phoneValue: { color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, recoveryCard: { gap: 8 }, cardTitle: { color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, cardDetail: { color: nwcColors.muted, fontSize: 12, lineHeight: 18, fontFamily: "Poppins_500Medium" }, code: { paddingVertical: 11, paddingHorizontal: 12, borderRadius: 15, backgroundColor: "#F1F6F7", borderWidth: 1, borderColor: "#DCE6E8" }, codeText: { color: nwcColors.brandNavy, fontSize: 15, lineHeight: 20, letterSpacing: 1.1, fontFamily: "Poppins_800ExtraBold" }, inlineAction: { alignSelf: "flex-start", minHeight: 34, justifyContent: "center" }, inlineActionText: { color: nwcColors.info, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_800ExtraBold" }, confirmed: { flexDirection: "row", alignItems: "center", gap: 6 }, confirmedText: { color: nwcColors.success, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_700Bold" }, actions: { gap: 10 },
});
