import { isValidPhoneInput } from "@/lib/auth-flow";
import { router, type Href } from "expo-router";
import { BookingScreen, BookingSection, FormField, OptionalDetails } from "@/components/booking/booking-ui";
import { useBookingDraft } from "@/stores/booking-draft";
import { recipientToBookingContact } from "@/lib/account-directory-booking";
import { useAddressBook } from "@/lib/use-cases/use-address-book";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { nwcColors } from "@/lib/nwc-theme";
import { isContactsReady } from "@/lib/booking-progress";

export default function LocalDeliveryContactsScreen() {
  const { localDraft, updateLocalDraft, setBookingStep } = useBookingDraft();
  const { recipients } = useAddressBook();
  const sender = localDraft.sender ?? { name: "", phone: "" };
  const receiver = localDraft.receiver ?? { name: "", phone: "" };
  const ready = isContactsReady({ ...localDraft, sender, receiver }) && isValidPhoneInput(sender.phone) && isValidPhoneInput(receiver.phone) && Boolean(sender.name.trim() && receiver.name.trim());
  const continueBooking = () => { setBookingStep("review"); router.push("/local-delivery/review" as Href); };
  return <BookingScreen activeStep="contacts" title="Who sends and receives it?" detail="We use these essentials to coordinate pickup and delivery." continueLabel="Review delivery" onContinue={continueBooking} continueDisabled={!ready}><BookingSection label="Sender"><FormField label="Your name" icon="account-outline" placeholder="Full name" value={sender.name} onContactPicked={(contact) => updateLocalDraft({ sender: { ...sender, name: contact.name || sender.name, phone: contact.phone } })} onChangeText={(name) => updateLocalDraft({ sender: { ...sender, name } })} /><FormField label="Your phone number" icon="phone-outline" placeholder="+260 …" keyboardType="phone-pad" value={sender.phone} onContactPicked={(contact) => updateLocalDraft({ sender: { ...sender, name: contact.name || sender.name, phone: contact.phone } })} onChangeText={(phone) => updateLocalDraft({ sender: { ...sender, phone } })} /></BookingSection><BookingSection label="Receiver">{recipients.length > 0 ? <><View style={styles.recipientHeader}><Text style={styles.savedLabel}>Saved recipients</Text><Text style={styles.savedHint}>Optional</Text></View><View style={styles.recipientChips}>{recipients.slice(0, 3).map((recipient) => <TouchableOpacity key={recipient.id} accessibilityRole="button" accessibilityLabel={`Use ${recipient.label} as recipient`} onPress={() => updateLocalDraft({ receiver: recipientToBookingContact(recipient) })} style={styles.recipientChip}><Text style={styles.recipientChipText}>{recipient.label}</Text></TouchableOpacity>)}</View></> : null}<FormField label="Receiver name" icon="account-outline" placeholder="Full name" value={receiver.name} onContactPicked={(contact) => updateLocalDraft({ receiver: { ...receiver, name: contact.name || receiver.name, phone: contact.phone } })} onChangeText={(name) => updateLocalDraft({ receiver: { ...receiver, name } })} /><FormField label="Receiver phone number" icon="phone-outline" placeholder="+260 …" keyboardType="phone-pad" value={receiver.phone} onContactPicked={(contact) => updateLocalDraft({ receiver: { ...receiver, name: contact.name || receiver.name, phone: contact.phone } })} onChangeText={(phone) => updateLocalDraft({ receiver: { ...receiver, phone } })} /></BookingSection>{sender.phone && !isValidPhoneInput(sender.phone) ? <Text accessibilityRole="alert" style={{ color: nwcColors.error }}>Enter a valid sender phone number.</Text> : null}{receiver.phone && !isValidPhoneInput(receiver.phone) ? <Text accessibilityRole="alert" style={{ color: nwcColors.error }}>Enter a valid receiver phone number.</Text> : null}<OptionalDetails label="Add delivery instructions"><FormField label="Instructions" icon="note-text-outline" placeholder="Entrance, landmark, or call on arrival" value={localDraft.deliveryInstructions ?? ""} onChangeText={(deliveryInstructions) => updateLocalDraft({ deliveryInstructions })} multiline /></OptionalDetails></BookingScreen>;
}

const styles = StyleSheet.create({
  recipientHeader: { marginBottom: -4, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, savedLabel: { color: nwcColors.foreground, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_800ExtraBold" }, savedHint: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" }, recipientChips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 2 }, recipientChip: { minHeight: 33, paddingHorizontal: 10, borderRadius: 11, justifyContent: "center", backgroundColor: nwcColors.surfaceNavyTint }, recipientChipText: { color: nwcColors.brandNavy, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_700Bold" },
});

