import { router, type Href } from "expo-router";
import { BookingScreen, BookingSection, ChoiceTile, FormField } from "@/components/booking/booking-ui";
import { useBookingDraft } from "@/stores/booking-draft";

export default function LocalDeliveryParcelScreen() {
  const { localDraft, updateLocalDraft, setBookingStep } = useBookingDraft();
  const continueBooking = () => { setBookingStep("contacts"); router.push("/local-delivery/contacts" as Href); };
  return <BookingScreen activeStep="parcel" title="Tell us about the parcel" detail="A clear description helps us handle your Katundu correctly." continueLabel="Continue to contacts" onContinue={continueBooking} continueDisabled={!localDraft.parcelCategory}><BookingSection label="Parcel type"><ChoiceTile title="Documents or small parcel" detail="Envelopes, accessories, or a hand-carry box." icon="package-variant-closed" selected={localDraft.parcelCategory === "small"} onPress={() => updateLocalDraft({ parcelCategory: "small" })} /><ChoiceTile title="Box or shopping items" detail="A standard carton, retail purchase, or household item." icon="package-variant" selected={localDraft.parcelCategory === "box"} onPress={() => updateLocalDraft({ parcelCategory: "box" })} /><ChoiceTile title="Special handling" detail="Fragile, valuable, or carefully packed item." icon="package-variant-closed" selected={localDraft.parcelCategory === "special"} onPress={() => updateLocalDraft({ parcelCategory: "special", handling: "fragile" })} /></BookingSection><BookingSection label="Parcel details"><FormField label="What are we carrying?" icon="text-box-outline" placeholder="e.g. Laptop accessories" value={localDraft.parcelDescription ?? ""} onChangeText={(parcelDescription) => updateLocalDraft({ parcelDescription })} multiline /><FormField label="Number of parcels" icon="numeric" placeholder="1" keyboardType="number-pad" value={localDraft.quantity ? String(localDraft.quantity) : ""} onChangeText={(value) => updateLocalDraft({ quantity: Math.max(1, Number(value) || 1) })} /></BookingSection></BookingScreen>;
}
