import { useState } from "react";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router, type Href } from "expo-router";

import { CustomerConfirmationDialog } from "@/components/ui/customer-confirmation-dialog";
import { AppIcon } from "@/components/ui/app-icon";
import { Card, IconButton, PrimaryButton, Screen, StatusBadge } from "@/components/ui/nwc-ui";
import { getCustomerApprovalPresentation } from "@/lib/customer-approval";
import { draftServiceColor, type MockBookingDraftRecord } from "@/lib/mock-booking-drafts";
import { nwcColors } from "@/lib/nwc-theme";
import { useBookingDraft } from "@/stores/booking-draft";

export default function BookingDraftsScreen() {
  const { savedDrafts, resumeSavedDraft, deleteSavedDraft } = useBookingDraft();
  const [removing, setRemoving] = useState<MockBookingDraftRecord | null>(null);
  const removal = getCustomerApprovalPresentation("remove-directory-item", removing?.title);
  const resume = (draft: MockBookingDraftRecord) => { const href = resumeSavedDraft(draft.id); if (href) router.push(href as Href); };
  return <Screen><View style={styles.page}><View style={styles.header}><IconButton label="Go back" icon="arrow-left" onPress={() => router.back()} /><Text style={styles.headerTitle}>Saved drafts</Text><View style={styles.headerSpacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.lead}><Text style={styles.title}>Continue a booking</Text><Text style={styles.detail}>Your unfinished cargo requests are kept here in this frontend preview.</Text></View>{savedDrafts.length ? <View style={styles.list}>{savedDrafts.map((draft) => <Card key={draft.id} style={styles.draft}><View style={styles.draftTop}><View style={[styles.serviceIcon, draftServiceColor(draft.service) === "yellow" ? styles.serviceYellow : draftServiceColor(draft.service) === "navy" ? styles.serviceNavy : styles.serviceTint]}><AppIcon name={draft.service === "local" ? "motorbike" : draft.service === "import" ? "package-variant-closed" : draft.service === "intercity" ? "truck-fast-outline" : "arrow-top-right"} size={21} color={draftServiceColor(draft.service) === "navy" ? nwcColors.white : nwcColors.brandNavy} /></View><View style={styles.draftCopy}><Text style={styles.draftTitle}>{draft.title}</Text><Text style={styles.draftRoute}>{draft.route}</Text></View><StatusBadge label={draft.progress} tone="info" /></View><View style={styles.draftBottom}><View><Text style={styles.step}>{draft.stepLabel}</Text><Text style={styles.updated}>{draft.updatedAt}</Text></View><View style={styles.actions}><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Delete ${draft.title} draft`} onPress={() => setRemoving(draft)} style={styles.delete}><Text style={styles.deleteText}>Delete</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Resume ${draft.title} draft`} onPress={() => resume(draft)} style={styles.resume}><Text style={styles.resumeText}>Resume</Text><AppIcon name="arrow-right" size={15} color={nwcColors.primaryInk} /></TouchableOpacity></View></View></Card>)}</View> : <Card style={styles.empty}><View style={styles.emptyIcon}><AppIcon name="clipboard-text-outline" size={25} color={nwcColors.primaryInk} /></View><Text style={styles.emptyTitle}>No saved bookings</Text><Text style={styles.emptyDetail}>Start a cargo request and it will appear here if you leave before confirming.</Text></Card>}<PrimaryButton label="Start a new booking" icon="plus" onPress={() => router.replace("/send" as Href)} /></ScrollView><CustomerConfirmationDialog visible={Boolean(removing)} {...removal} approveLabel="Delete draft" onDismiss={() => setRemoving(null)} onApprove={() => { if (removing) deleteSavedDraft(removing.id); setRemoving(null); }} /></View></Screen>;
}

const styles = StyleSheet.create({
  page: { flex: 1, paddingTop: 16, paddingHorizontal: 20, backgroundColor: nwcColors.background }, header: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { color: nwcColors.brandNavy, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" }, headerSpacer: { width: 44, height: 44 }, content: { paddingTop: 24, paddingBottom: 42, gap: 16 }, lead: { gap: 4 }, title: { color: nwcColors.foreground, fontSize: 29, lineHeight: 37, letterSpacing: -0.5, fontFamily: "Poppins_800ExtraBold" }, detail: { color: nwcColors.muted, fontSize: 13, lineHeight: 19, fontFamily: "Poppins_500Medium" }, list: { gap: 10 }, draft: { gap: 14, padding: 14 }, draftTop: { flexDirection: "row", alignItems: "center", gap: 10 }, serviceIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, serviceYellow: { backgroundColor: nwcColors.primary }, serviceNavy: { backgroundColor: nwcColors.brandNavy }, serviceTint: { backgroundColor: nwcColors.surfaceNavyTint }, draftCopy: { flex: 1, gap: 1 }, draftTitle: { color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" }, draftRoute: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, draftBottom: { paddingTop: 11, borderTopWidth: 1, borderTopColor: "#E5ECEE", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 }, step: { color: nwcColors.foreground, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_700Bold" }, updated: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_500Medium" }, actions: { flexDirection: "row", alignItems: "center", gap: 8 }, delete: { minHeight: 34, justifyContent: "center", paddingHorizontal: 5 }, deleteText: { color: nwcColors.error, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_800ExtraBold" }, resume: { minHeight: 34, paddingHorizontal: 11, borderRadius: 12, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 4, backgroundColor: nwcColors.primary }, resumeText: { color: nwcColors.primaryInk, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_800ExtraBold" }, empty: { alignItems: "center", gap: 6, paddingVertical: 28 }, emptyIcon: { width: 54, height: 54, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.primary }, emptyTitle: { color: nwcColors.foreground, fontSize: 16, lineHeight: 22, fontFamily: "Poppins_800ExtraBold" }, emptyDetail: { maxWidth: 264, color: nwcColors.muted, textAlign: "center", fontSize: 12, lineHeight: 18, fontFamily: "Poppins_500Medium" },
});
