import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { router, useLocalSearchParams, type Href } from "expo-router";

import { AppIcon } from "@/components/ui/app-icon";
import { IconButton, PrimaryButton, Screen, StatusBadge } from "@/components/ui/nwc-ui";
import { nwcColors } from "@/lib/nwc-theme";
import { useMockBilling } from "@/stores/mock-billing";

export default function InvoiceDetailScreen() {
  const { invoiceId } = useLocalSearchParams<{ invoiceId: string }>();
  const { invoices, selectInvoice } = useMockBilling();
  const invoice = invoices.find((item) => item.id === invoiceId) ?? invoices[0];
  const pay = () => { selectInvoice(invoice.id); router.push("/bills/payment" as Href); };
  const documentAction = (kind: "invoice" | "receipt") => Alert.alert(`${kind === "invoice" ? "Invoice" : "Receipt"} preview`, `A ${kind} document for ${invoice.reference} will be downloaded or shared when the document service is connected. This mock keeps the customer action visible.`);
  return <Screen><View style={styles.page}><View style={styles.header}><IconButton label="Go back" icon="arrow-left" onPress={() => router.back()} /><Text style={styles.headerTitle}>Invoice</Text><View style={styles.headerSpacer} /></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.titleBlock}><Text style={styles.eyebrow}>Invoice details</Text><Text style={styles.title}>{invoice.reference}</Text></View><View style={styles.summary}><View style={styles.summaryHead}><View style={styles.summaryIcon}><AppIcon name="package-variant-closed" size={21} color={nwcColors.primaryInk} /></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>{invoice.shipmentLabel}</Text><Text style={styles.summaryRoute}>{invoice.route}</Text></View><StatusBadge label={invoice.status === "paid" ? "Paid" : "Due"} tone={invoice.status === "paid" ? "success" : "warning"} /></View><View style={styles.dates}><DateCell label="Issued" value={invoice.issuedAt} /><DateCell label={invoice.status === "paid" ? "Paid on" : "Due on"} value={invoice.status === "paid" ? invoice.paidAt ?? "Confirmed" : invoice.dueAt ?? "To confirm"} /></View></View><View style={styles.charges}><Text style={styles.chargesLabel}>Charges</Text>{invoice.lineItems.map((item) => <View key={item.label} style={styles.chargeRow}><View style={styles.chargeCopy}><Text style={styles.chargeTitle}>{item.label}</Text>{item.detail ? <Text style={styles.chargeDetail}>{item.detail}</Text> : null}</View><Text style={styles.chargeAmount}>{item.amount}</Text></View>)}<View style={styles.total}><Text style={styles.totalLabel}>Total</Text><Text style={styles.totalAmount}>{invoice.amount}</Text></View></View><View style={[styles.context, invoice.status === "paid" ? styles.contextPaid : styles.contextDue]}><AppIcon name={invoice.status === "paid" ? "check-circle-outline" : "alert-circle-outline"} size={19} color={invoice.status === "paid" ? nwcColors.success : nwcColors.warning} /><View style={styles.contextCopy}><Text style={styles.contextTitle}>{invoice.status === "paid" ? "Payment received" : "Payment still due"}</Text><Text style={styles.contextDetail}>{invoice.status === "paid" ? `${invoice.paymentMethod ?? "Payment"}. Your receipt is ready for your records.` : "Review the charges and choose a mock payment method when ready."}</Text></View></View><View style={styles.documentActions}><DocumentAction label="Invoice" icon="file-document-outline" onPress={() => documentAction("invoice")} />{invoice.status === "paid" ? <DocumentAction label="Receipt" icon="download-outline" onPress={() => documentAction("receipt")} /> : null}</View>{invoice.status === "unpaid" ? <PrimaryButton label={`Pay ${invoice.amount}`} icon="arrow-right" onPress={pay} /> : <PrimaryButton label="View receipt" icon="receipt-text-outline" onPress={() => router.push("/bills/receipt" as Href)} />}</ScrollView></View></Screen>;
}

function DateCell({ label, value }: { label: string; value: string }) { return <View style={styles.dateCell}><Text style={styles.dateLabel}>{label}</Text><Text style={styles.dateValue}>{value}</Text></View>; }
function DocumentAction({ label, icon, onPress }: { label: string; icon: Parameters<typeof AppIcon>[0]["name"]; onPress: () => void }) { return <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Download or share ${label.toLowerCase()}`} onPress={onPress} activeOpacity={0.74} style={styles.documentAction}><AppIcon name={icon} size={19} color={nwcColors.brandNavy} /><Text style={styles.documentText}>{label}</Text><AppIcon name="share-variant-outline" size={17} color={nwcColors.muted} /></TouchableOpacity>; }

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: nwcColors.background, paddingHorizontal: 20, paddingTop: 16 }, header: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { color: nwcColors.brandNavy, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" }, headerSpacer: { width: 44, height: 44 }, content: { paddingTop: 22, paddingBottom: 48, gap: 16 }, titleBlock: { gap: 3 }, eyebrow: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_700Bold", textTransform: "uppercase", letterSpacing: 0.6 }, title: { color: nwcColors.foreground, fontSize: 29, lineHeight: 37, fontFamily: "Poppins_800ExtraBold", letterSpacing: -0.5 },
  summary: { gap: 14, padding: 15, borderRadius: 23, backgroundColor: "#F2F7F8", borderWidth: 1, borderColor: "#DFE9EB" }, summaryHead: { flexDirection: "row", alignItems: "flex-start", gap: 10 }, summaryIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.primary }, summaryCopy: { flex: 1, gap: 2 }, summaryTitle: { color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, summaryRoute: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, dates: { flexDirection: "row", gap: 18, paddingTop: 13, borderTopWidth: 1, borderTopColor: "#DDE6E8" }, dateCell: { flex: 1, gap: 2 }, dateLabel: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" }, dateValue: { color: nwcColors.foreground, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_800ExtraBold" },
  charges: { gap: 0, padding: 15, borderRadius: 23, backgroundColor: nwcColors.surface, borderWidth: 1, borderColor: "#E5EBED" }, chargesLabel: { marginBottom: 4, color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_700Bold", textTransform: "uppercase", letterSpacing: 0.55 }, chargeRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 15, paddingVertical: 12, borderTopWidth: 1, borderTopColor: "#E8EEEF" }, chargeCopy: { flex: 1, gap: 2 }, chargeTitle: { color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_700Bold" }, chargeDetail: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_500Medium" }, chargeAmount: { color: nwcColors.brandNavy, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" }, total: { marginTop: 2, paddingTop: 13, borderTopWidth: 1.5, borderTopColor: "#C8D5D9", flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, totalLabel: { color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, totalAmount: { color: nwcColors.brandNavy, fontSize: 21, lineHeight: 27, fontFamily: "Poppins_800ExtraBold" },
  context: { padding: 14, borderRadius: 19, flexDirection: "row", alignItems: "flex-start", gap: 9 }, contextDue: { backgroundColor: "#FFF4DA" }, contextPaid: { backgroundColor: "#EAF7F0" }, contextCopy: { flex: 1, gap: 2 }, contextTitle: { color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" }, contextDetail: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" },
  documentActions: { flexDirection: "row", gap: 9 }, documentAction: { flex: 1, minHeight: 48, borderRadius: 16, paddingHorizontal: 11, flexDirection: "row", alignItems: "center", gap: 7, backgroundColor: nwcColors.surface, borderWidth: 1, borderColor: "#E1E8EA" }, documentText: { flex: 1, color: nwcColors.brandNavy, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_800ExtraBold" },
});
