import { useState } from "react";
import { StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AppIcon, type AppIconName } from "@/components/ui/app-icon";
import { nwcColors } from "@/lib/nwc-theme";
import { statusPresentation } from "@/lib/mock-cargo-data";
import type { LiveTrackingHistoryEvent } from "@/lib/live-tracking-history";
import { copyTrackingNumber, shareTrackingNumber } from "@/lib/customer-tracking-actions";
import type { Shipment, TrackingContact } from "@/types/cargo";

export function LiveShipmentContextCard({ shipment }: { shipment: Shipment }) {
  const status = statusPresentation[shipment.status];
  return <View style={styles.contextCard}><View style={styles.contextTop}><View><Text style={styles.contextReference}>{shipment.reference}</Text><Text numberOfLines={1} style={styles.contextTitle}>{shipment.title}</Text></View><View style={styles.contextStatus}><AppIcon name={status.icon as AppIconName} size={14} color={nwcColors.primaryInk} /><Text style={styles.contextStatusText}>{status.label}</Text></View></View><View style={styles.contextRoute}><View style={styles.contextPlace}><Text style={styles.contextPlaceLabel}>From</Text><Text numberOfLines={1} style={styles.contextPlaceValue}>{shipment.pickup.area}</Text><Text numberOfLines={1} style={styles.contextPlaceDetail}>{shipment.pickup.city}</Text></View><View style={styles.contextConnector}><View style={styles.contextLine} /><AppIcon name="arrow-right" size={16} color={nwcColors.info} /></View><View style={[styles.contextPlace, styles.contextPlaceEnd]}><Text style={styles.contextPlaceLabel}>To</Text><Text numberOfLines={1} style={styles.contextPlaceValue}>{shipment.destination.area}</Text><Text numberOfLines={1} style={styles.contextPlaceDetail}>{shipment.destination.city}</Text></View></View></View>;
}

export function TrackingHistoryPanel({ events, open, onToggle }: { events: LiveTrackingHistoryEvent[]; open: boolean; onToggle: () => void }) {
  return <View style={styles.historyCard}><TouchableOpacity accessibilityRole="button" accessibilityLabel={open ? "Hide tracking history" : "View tracking history"} accessibilityState={{ expanded: open }} activeOpacity={0.74} onPress={onToggle} style={styles.historyToggle}><View><Text style={styles.historyTitle}>Tracking history</Text><Text style={styles.historyDetail}>{open ? "Latest shipment movement and next handover" : `${events.length} updates · tap to view`}</Text></View><View style={styles.historyToggleIcon}><AppIcon name={open ? "chevron-up" : "chevron-down"} size={20} color={nwcColors.brandNavy} /></View></TouchableOpacity>{open ? <View style={styles.historyList}>{events.map((event, index) => <View key={event.id} style={styles.historyItem}>{index < events.length - 1 ? <View style={[styles.historyLine, event.state !== "upcoming" && styles.historyLineComplete]} /> : null}<View style={[styles.historyDot, event.state === "complete" && styles.historyDotComplete, event.state === "current" && styles.historyDotCurrent]}>{event.state !== "upcoming" ? <AppIcon name="check" size={10} color={event.state === "current" ? nwcColors.primaryInk : nwcColors.white} /> : null}</View><View style={styles.historyCopy}><View style={styles.historyLabelLine}><Text style={styles.historyEventTitle}>{event.label}</Text>{event.state === "current" ? <Text style={styles.historyCurrent}>Now</Text> : null}</View><Text style={styles.historyEventDetail}>{event.detail}</Text><Text style={styles.historyTime}>{event.time}</Text></View></View>)}</View> : null}</View>;
}

export function TrackingReferenceActions({ reference }: { reference: string }) {
  const [feedback, setFeedback] = useState<string>();
  const copy = async () => { const result = await copyTrackingNumber(reference); setFeedback(result.message); };
  const share = async () => { const result = await shareTrackingNumber(reference); setFeedback(result.message); };
  return <View style={styles.referenceActions}><View style={styles.referenceActionRow}><TouchableOpacity accessibilityRole="button" accessibilityLabel="Copy tracking number" activeOpacity={0.74} onPress={copy} style={styles.referenceAction}><AppIcon name="content-copy" size={18} color={nwcColors.brandNavy} /><Text style={styles.referenceActionText}>Copy number</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="Share tracking" activeOpacity={0.74} onPress={share} style={styles.referenceAction}><AppIcon name="share-variant-outline" size={18} color={nwcColors.brandNavy} /><Text style={styles.referenceActionText}>Share tracking</Text></TouchableOpacity></View>{feedback ? <Text style={styles.referenceFeedback}>{feedback}</Text> : null}</View>;
}

export function TrackingContactCard({ contact, onMessage, onCall }: { contact: TrackingContact; onMessage: () => void; onCall: () => void }) {
  const initials = contact.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  return <View style={styles.contactCard}><View style={styles.contactAvatar}><Text style={styles.contactInitials}>{initials}</Text></View><View style={styles.contactCopy}><View style={styles.contactNameLine}><Text numberOfLines={1} style={styles.contactName}>{contact.name}</Text>{contact.rating ? <View style={styles.rating}><AppIcon name="star" size={13} color={nwcColors.primary} /><Text style={styles.ratingText}>{contact.rating}</Text></View> : null}</View><Text numberOfLines={1} style={styles.contactRole}>{contact.role}</Text>{contact.verified ? <View style={styles.verified}><AppIcon name="shield-check-outline" size={13} color={nwcColors.brandNavy} /><Text style={styles.verifiedText}>Verified</Text></View> : null}</View><View style={styles.contactActions}><CircleAction label={`Message ${contact.name}`} icon="message-text-outline" onPress={onMessage} /><CircleAction label={`Call ${contact.name}`} icon="phone-outline" onPress={onCall} /></View></View>;
}

export function DeliveryProgressCard({ shipment }: { shipment: Shipment }) {
  const progress = shipment.trackingProgress ?? { fraction: 0.5, distanceLabel: "On the way", pickupTime: "Picked up", arrivalTime: shipment.eta, stages: [] };
  const status = shipment.status === "out_for_delivery" ? "Out for delivery" : shipment.status === "in_transit" ? "In transit" : "Booking confirmed";
  return <View style={styles.progressCard}><View style={styles.progressHeader}><View style={styles.destinationCopy}><Text style={styles.progressEyebrow}>Delivery destination</Text><Text numberOfLines={1} style={styles.destinationTitle}>{shipment.destination.detail}</Text><Text numberOfLines={1} style={styles.destinationSubline}>{shipment.destination.area}, {shipment.destination.city}</Text></View><View style={styles.statusPill}><AppIcon name={shipment.status === "out_for_delivery" ? "truck-delivery-outline" : "truck-fast-outline"} size={14} color={nwcColors.primaryInk} /><Text style={styles.statusPillText}>{status}</Text></View></View><View style={styles.distance}><AppIcon name="map-marker-distance" size={18} color={nwcColors.muted} /><Text style={styles.distanceText}>{progress.distanceLabel}</Text></View><View style={styles.progressRail}><View style={[styles.progressFill, { width: `${Math.max(6, Math.min(100, progress.fraction * 100))}%` }]} /><View style={[styles.progressMarker, { left: `${Math.max(2, Math.min(94, progress.fraction * 100))}%` }]} /><View style={styles.progressEnd} /></View><View style={styles.progressTimes}><View><Text style={styles.timeValue}>{progress.pickupTime}</Text><Text style={styles.timeLabel}>Picked up</Text></View><View style={styles.timeEnd}><Text style={styles.timeValue}>{progress.arrivalTime}</Text><Text style={styles.timeLabel}>Estimated arrival</Text></View></View></View>;
}

export function TrackingActionList({ onOrder, onPayment, onSupport, onPickup, onDelivery }: { onOrder: () => void; onPayment: () => void; onSupport: () => void; onPickup?: () => void; onDelivery?: () => void }) {
  const rows: { label: string; icon: AppIconName; onPress: () => void }[] = [...(onPickup ? [{ label: "Manage pickup", icon: "clock-time-four-outline" as AppIconName, onPress: onPickup }] : []), ...(onDelivery ? [{ label: "Manage delivery", icon: "truck-fast-outline" as AppIconName, onPress: onDelivery }] : []), { label: "Order details", icon: "clipboard-text-outline", onPress: onOrder }, { label: "Payment details", icon: "credit-card-outline", onPress: onPayment }, { label: "Support", icon: "lifebuoy", onPress: onSupport }];
  return <View style={styles.actionList}>{rows.map((row, index) => <TouchableOpacity key={row.label} accessibilityRole="button" accessibilityLabel={row.label} activeOpacity={0.72} onPress={row.onPress} style={[styles.actionRow, index !== rows.length - 1 && styles.actionDivider]}><View style={styles.actionIcon}><AppIcon name={row.icon} size={21} color={nwcColors.brandNavy} /></View><Text style={styles.actionLabel}>{row.label}</Text><AppIcon name="chevron-right" size={22} color={nwcColors.muted} /></TouchableOpacity>)}</View>;
}

export function DeliveryInstructionsCard({ initialValue, onSaved }: { initialValue?: string; onSaved: (value: string) => void }) {
  const [value, setValue] = useState(initialValue ?? "");
  const [saved, setSaved] = useState(false);
  const save = () => { onSaved(value.trim()); setSaved(true); };
  return <View style={styles.instructionsCard}><View style={styles.instructionsHead}><View style={styles.instructionsIcon}><AppIcon name="message-text-outline" size={20} color={nwcColors.primaryInk} /></View><View style={styles.instructionsCopy}><Text style={styles.instructionsTitle}>Delivery instructions</Text><Text style={styles.instructionsDetail}>Share a gate, landmark, or safe drop-off note.</Text></View></View><TextInput accessibilityLabel="Delivery instructions" value={value} onChangeText={(next) => { setValue(next); setSaved(false); }} placeholder="e.g. Call at the gate; blue office block" placeholderTextColor="#90A0AA" multiline maxLength={140} style={styles.instructionsInput} /><TouchableOpacity accessibilityRole="button" accessibilityLabel="Save delivery instructions" activeOpacity={0.74} onPress={save} style={[styles.instructionsButton, saved && styles.instructionsButtonSaved]}><AppIcon name={saved ? "check" : "send-outline"} size={17} color={nwcColors.primaryInk} /><Text style={styles.instructionsButtonText}>{saved ? "Instructions saved" : "Save instructions"}</Text></TouchableOpacity></View>;
}

export function ProofOfDeliveryCard({ shipment, onDownload }: { shipment: Shipment; onDownload?: () => void }) {
  const recipient = shipment.service === "local" ? "M. Banda" : "Receiving contact";
  return <View style={styles.proofCard}><View style={styles.proofHead}><View style={styles.proofIcon}><AppIcon name="check-decagram" size={22} color={nwcColors.white} /></View><View style={styles.proofCopy}><Text style={styles.proofEyebrow}>Proof of delivery</Text><Text style={styles.proofTitle}>Delivered and confirmed</Text></View></View><View style={styles.proofEvidence}><View style={styles.proofPhoto}><AppIcon name="image-outline" size={25} color={nwcColors.info} /><Text style={styles.proofPhotoText}>Drop-off photo</Text></View><View style={styles.signature}><Text style={styles.signatureName}>{recipient}</Text><Text style={styles.signatureCaption}>Recipient signature</Text></View></View><Text style={styles.proofTime}>Confirmed at the destination · 28 Aug, 15:46</Text>{onDownload ? <TouchableOpacity accessibilityRole="button" accessibilityLabel="Download proof of delivery" activeOpacity={0.74} onPress={onDownload} style={styles.proofDownload}><AppIcon name="share-variant-outline" size={17} color={nwcColors.brandNavy} /><Text style={styles.proofDownloadText}>Download proof</Text></TouchableOpacity> : null}</View>;
}

function CircleAction({ label, icon, onPress }: { label: string; icon: AppIconName; onPress: () => void }) {
  return <TouchableOpacity accessibilityRole="button" accessibilityLabel={label} activeOpacity={0.7} onPress={onPress} style={styles.circleAction}><AppIcon name={icon} size={21} color={nwcColors.brandNavy} /></TouchableOpacity>;
}

const styles = StyleSheet.create({
  contactCard: { minHeight: 110, borderRadius: 23, backgroundColor: nwcColors.surface, padding: 14, flexDirection: "row", alignItems: "center", gap: 11, borderWidth: 1, borderColor: "#E5EBED" },
  contextCard: { gap: 14, padding: 15, borderRadius: 23, backgroundColor: nwcColors.surface, borderWidth: 1, borderColor: "#E3EAEC" }, contextTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 }, contextReference: { color: nwcColors.info, fontSize: 10, lineHeight: 14, letterSpacing: 0.6, fontFamily: "Poppins_800ExtraBold" }, contextTitle: { marginTop: 2, maxWidth: 176, color: nwcColors.foreground, fontSize: 17, lineHeight: 23, fontFamily: "Poppins_800ExtraBold" }, contextStatus: { maxWidth: 126, borderRadius: 11, paddingHorizontal: 8, paddingVertical: 6, flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: nwcColors.primary }, contextStatusText: { color: nwcColors.primaryInk, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_800ExtraBold" }, contextRoute: { flexDirection: "row", alignItems: "center", gap: 8 }, contextPlace: { flex: 1, gap: 1 }, contextPlaceEnd: { alignItems: "flex-end" }, contextPlaceLabel: { color: nwcColors.muted, fontSize: 9, lineHeight: 12, textTransform: "uppercase", letterSpacing: 0.5, fontFamily: "Poppins_700Bold" }, contextPlaceValue: { maxWidth: 104, color: nwcColors.foreground, fontSize: 14, lineHeight: 19, fontFamily: "Poppins_800ExtraBold" }, contextPlaceDetail: { maxWidth: 104, color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_500Medium" }, contextConnector: { width: 39, alignItems: "center", justifyContent: "center" }, contextLine: { position: "absolute", left: 0, right: 0, height: 1, backgroundColor: "#CAD8DD" },
  contactAvatar: { width: 58, height: 58, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.brandNavy, borderWidth: 3, borderColor: nwcColors.primary },
  contactInitials: { color: nwcColors.white, fontSize: 16, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" },
  contactCopy: { minWidth: 0, flex: 1, gap: 2 },
  contactNameLine: { flexDirection: "row", alignItems: "center", gap: 7 },
  contactName: { maxWidth: 106, color: nwcColors.foreground, fontSize: 16, lineHeight: 21, fontFamily: "Poppins_800ExtraBold" },
  rating: { flexDirection: "row", alignItems: "center", gap: 2 },
  ratingText: { color: nwcColors.foreground, fontSize: 12, lineHeight: 16, fontFamily: "Poppins_700Bold" },
  contactRole: { color: nwcColors.muted, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_500Medium" },
  verified: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 3, borderRadius: 7, backgroundColor: "#EDF3F4", paddingHorizontal: 6, paddingVertical: 3 },
  verifiedText: { color: nwcColors.brandNavy, fontSize: 9, lineHeight: 12, fontFamily: "Poppins_800ExtraBold" },
  contactActions: { flexDirection: "row", gap: 7 },
  circleAction: { width: 43, height: 43, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#F1F5F6" },
  progressCard: { borderRadius: 24, backgroundColor: nwcColors.surface, padding: 17, gap: 13, borderWidth: 1, borderColor: "#E5EBED" },
  progressHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 9 },
  destinationCopy: { flex: 1, gap: 1 },
  progressEyebrow: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_700Bold", textTransform: "uppercase", letterSpacing: 0.5 },
  destinationTitle: { color: nwcColors.foreground, fontSize: 18, lineHeight: 24, fontFamily: "Poppins_800ExtraBold" },
  destinationSubline: { color: nwcColors.muted, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_500Medium" },
  statusPill: { maxWidth: 125, borderRadius: 11, backgroundColor: nwcColors.primary, paddingHorizontal: 8, paddingVertical: 7, flexDirection: "row", alignItems: "center", gap: 4 },
  statusPillText: { color: nwcColors.primaryInk, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_800ExtraBold" },
  distance: { flexDirection: "row", alignItems: "center", gap: 5 },
  distanceText: { color: nwcColors.muted, fontSize: 12, lineHeight: 16, fontFamily: "Poppins_600SemiBold" },
  progressRail: { position: "relative", height: 24, marginTop: 1, justifyContent: "center", backgroundColor: "transparent" },
  progressFill: { position: "absolute", left: 0, height: 4, borderRadius: 2, backgroundColor: nwcColors.primary },
  progressMarker: { position: "absolute", top: 2, width: 21, height: 21, borderRadius: 11, borderWidth: 4, borderColor: nwcColors.primary, backgroundColor: nwcColors.brandNavy },
  progressEnd: { position: "absolute", right: 0, width: 14, height: 14, borderRadius: 7, backgroundColor: "#DDE3E5" },
  progressTimes: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  timeEnd: { alignItems: "flex-end", flex: 1 },
  timeValue: { color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" },
  timeLabel: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_500Medium" },
  actionList: { borderRadius: 23, overflow: "hidden", backgroundColor: nwcColors.surface, borderWidth: 1, borderColor: "#E5EBED", paddingHorizontal: 14 },
  historyCard: { overflow: "hidden", borderRadius: 23, backgroundColor: nwcColors.surface, borderWidth: 1, borderColor: "#E5EBED" }, historyToggle: { minHeight: 72, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, historyTitle: { color: nwcColors.foreground, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" }, historyDetail: { marginTop: 2, color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, historyToggleIcon: { width: 36, height: 36, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#EDF3F4" }, historyList: { borderTopWidth: 1, borderTopColor: "#E9EEEF", paddingHorizontal: 16, paddingTop: 16, paddingBottom: 4 }, historyItem: { position: "relative", minHeight: 71, flexDirection: "row", gap: 12 }, historyLine: { position: "absolute", left: 8, top: 20, bottom: -2, width: 2, backgroundColor: "#DCE4E7" }, historyLineComplete: { backgroundColor: nwcColors.primary }, historyDot: { zIndex: 1, marginTop: 1, width: 18, height: 18, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.white, borderWidth: 2, borderColor: "#D0DADF" }, historyDotComplete: { backgroundColor: nwcColors.brandNavy, borderColor: nwcColors.brandNavy }, historyDotCurrent: { backgroundColor: nwcColors.primary, borderColor: nwcColors.primary }, historyCopy: { flex: 1, gap: 1, paddingBottom: 14 }, historyLabelLine: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, historyEventTitle: { flex: 1, color: nwcColors.foreground, fontSize: 13, lineHeight: 18, fontFamily: "Poppins_800ExtraBold" }, historyCurrent: { borderRadius: 7, paddingHorizontal: 6, paddingVertical: 2, color: nwcColors.primaryInk, backgroundColor: nwcColors.primary, fontSize: 9, lineHeight: 12, fontFamily: "Poppins_800ExtraBold" }, historyEventDetail: { color: nwcColors.muted, fontSize: 11, lineHeight: 16, fontFamily: "Poppins_500Medium" }, historyTime: { marginTop: 2, color: nwcColors.info, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" },
  referenceActions: { gap: 7 }, referenceActionRow: { flexDirection: "row", gap: 9 }, referenceAction: { flex: 1, minHeight: 47, paddingHorizontal: 12, borderRadius: 16, backgroundColor: "#F0F5F6", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, referenceActionText: { color: nwcColors.brandNavy, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_800ExtraBold" }, referenceFeedback: { color: nwcColors.info, textAlign: "center", fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" },
  actionRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 12 },
  actionDivider: { borderBottomWidth: 1, borderBottomColor: "#E9EEEF" },
  actionIcon: { width: 32, alignItems: "center" },
  actionLabel: { flex: 1, color: nwcColors.foreground, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_700Bold" },
  instructionsCard: { gap: 12, borderRadius: 23, backgroundColor: nwcColors.surface, padding: 15, borderWidth: 1, borderColor: "#E5EBED" }, instructionsHead: { flexDirection: "row", gap: 10, alignItems: "center" }, instructionsIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.primary }, instructionsCopy: { flex: 1, gap: 1 }, instructionsTitle: { color: nwcColors.foreground, fontSize: 15, lineHeight: 20, fontFamily: "Poppins_800ExtraBold" }, instructionsDetail: { color: nwcColors.muted, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_500Medium" }, instructionsInput: { minHeight: 66, borderRadius: 14, borderWidth: 1, borderColor: "#DFE8EA", backgroundColor: "#F8FAFA", paddingHorizontal: 11, paddingVertical: 10, color: nwcColors.foreground, fontSize: 12, lineHeight: 17, fontFamily: "Poppins_500Medium", textAlignVertical: "top" }, instructionsButton: { alignSelf: "flex-start", minHeight: 36, borderRadius: 12, paddingHorizontal: 11, flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: nwcColors.primary }, instructionsButtonSaved: { backgroundColor: "#DDF3E9" }, instructionsButtonText: { color: nwcColors.primaryInk, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_800ExtraBold" },
  proofCard: { gap: 13, borderRadius: 23, backgroundColor: "#F0F8F4", padding: 16, borderWidth: 1, borderColor: "#CFE9DB" }, proofHead: { flexDirection: "row", alignItems: "center", gap: 10 }, proofIcon: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: nwcColors.success }, proofCopy: { gap: 1 }, proofEyebrow: { color: nwcColors.success, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_700Bold", textTransform: "uppercase", letterSpacing: 0.45 }, proofTitle: { color: nwcColors.foreground, fontSize: 16, lineHeight: 21, fontFamily: "Poppins_800ExtraBold" }, proofEvidence: { flexDirection: "row", gap: 10 }, proofPhoto: { flex: 1, minHeight: 88, borderRadius: 16, alignItems: "center", justifyContent: "center", gap: 4, backgroundColor: "#DCE9EC", borderWidth: 1, borderColor: "#C7D9DD" }, proofPhotoText: { color: nwcColors.info, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_700Bold" }, signature: { flex: 1, minHeight: 88, borderRadius: 16, justifyContent: "center", paddingHorizontal: 12, backgroundColor: nwcColors.white, borderWidth: 1, borderColor: "#D7E8DE" }, signatureName: { color: nwcColors.brandNavy, fontSize: 20, lineHeight: 26, fontFamily: "Poppins_500Medium", fontStyle: "italic" }, signatureCaption: { marginTop: 6, color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" }, proofTime: { color: nwcColors.muted, fontSize: 10, lineHeight: 14, fontFamily: "Poppins_600SemiBold" }, proofDownload: { alignSelf: "flex-start", minHeight: 35, paddingHorizontal: 10, borderRadius: 11, backgroundColor: nwcColors.surfaceElevated, flexDirection: "row", alignItems: "center", gap: 5 }, proofDownloadText: { color: nwcColors.brandNavy, fontSize: 11, lineHeight: 15, fontFamily: "Poppins_800ExtraBold" },
});
