import { router, useLocalSearchParams } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { AppIcon } from "@/components/ui/app-icon";
import { PrimaryButton, Screen, SecondaryButton } from "@/components/ui/nwc-ui";
import { nwcColors } from "@/lib/nwc-theme";
import { useBookingDraft } from "@/stores/booking-draft";

export default function CustomConfirmationScreen() { const { resetCustomDraft } = useBookingDraft(); const { shipmentId, reference } = useLocalSearchParams<{ shipmentId?: string; reference?: string }>(); const home = () => { resetCustomDraft(); router.replace("/" as never); }; const openShipment = () => { resetCustomDraft(); router.replace((shipmentId ? `/shipments/${shipmentId}` : "/shipments") as never); }; return <Screen><View style={styles.page}><View style={styles.hero}><View style={styles.icon}><AppIcon name="check" size={33} color={nwcColors.primaryInk} /></View>{reference ? <Text style={styles.reference}>Booking reference {reference}</Text> : null}<Text style={styles.title}>Custom request received</Text><Text style={styles.detail}>A New WorldCargo team member will review your route and request, then share the right next step.</Text></View><View style={styles.actions}><PrimaryButton label={shipmentId ? "Open shipment" : "View shipments"} onPress={openShipment} /><SecondaryButton label="Back to Home" onPress={home} /></View></View></Screen>; }
const styles = StyleSheet.create({ page: { flex: 1, justifyContent: "space-between", padding: 28, backgroundColor: nwcColors.background }, hero: { alignItems: "center", gap: 12, paddingTop: 96 }, icon: { height: 76, width: 76, borderRadius: 26, backgroundColor: nwcColors.primary, alignItems: "center", justifyContent: "center" }, reference: { color: nwcColors.info, fontSize: 12, lineHeight: 16, fontFamily: "Poppins_800ExtraBold", letterSpacing: 0.6, textTransform: "uppercase", textAlign: "center" }, title: { color: nwcColors.foreground, fontSize: 26, lineHeight: 33, fontFamily: "Poppins_800ExtraBold", textAlign: "center" }, detail: { color: nwcColors.muted, fontSize: 14, lineHeight: 21, fontFamily: "Poppins_500Medium", textAlign: "center" }, actions: { gap: 10 } });
