import { useState } from "react";
import { router } from "expo-router";
import { BookingMapRouteShell } from "@/components/booking/booking-map-route-shell";
import { BookingSection, FormField } from "@/components/booking/booking-ui";
import { RouteEntryCard } from "@/components/booking/route-entry-card";
import { isRouteComplete } from "@/lib/service-booking";
import { routeSuggestionToAddress } from "@/lib/route-autocomplete";
import { useBookingDraft } from "@/stores/booking-draft";

const customSteps = [{ id: "route", label: "Route" }, { id: "details", label: "Details" }, { id: "review", label: "Review" }];

export default function CustomRouteScreen() { const { customDraft, updateCustomDraft } = useBookingDraft(); const [editing, setEditing] = useState<"from" | "to" | null>(null); const activePoint = editing === "to" ? "destination" : "pickup"; const routeReady = isRouteComplete(customDraft.pickup, customDraft.destination); const updatePoint = (target: "pickup" | "destination", field: "city" | "area" | "detail", value: string) => { const current = customDraft[target] ?? { city: "Lusaka", area: "", detail: "" }; updateCustomDraft({ [target]: { ...current, [field]: value } }); }; return <BookingMapRouteShell service="custom" activeStep="route" serviceLabel="Custom Request" progressSteps={customSteps} title="Where should we move it?" detail="Search pickup and destination first. The map reacts immediately while you edit the bottom sheet." pickup={customDraft.pickup} destination={customDraft.destination} routeReady={routeReady} continueLabel="Continue to details" continueDisabled={!routeReady} onContinue={() => router.push("/custom/details" as never)}><RouteEntryCard scope="custom" from={{ value: customDraft.pickup?.detail ?? "", detail: customDraft.pickup?.area ?? "" }} to={{ value: customDraft.destination?.detail ?? "", detail: customDraft.destination?.area ?? "" }} onSuggestionSelect={(target, suggestion) => updateCustomDraft({ [target === "from" ? "pickup" : "destination"]: routeSuggestionToAddress(suggestion) })} onManualEntryPress={setEditing} accessibilityHint="Set the custom request pickup and destination" />{editing ? <BookingSection label={editing === "from" ? "Manual pickup" : "Manual destination"}><FormField label="Area" icon="map-marker-outline" placeholder={editing === "from" ? "e.g. Longacres" : "e.g. City or suburb"} value={customDraft[activePoint]?.area ?? ""} onChangeText={(value) => updatePoint(activePoint, "area", value)} /><FormField label="Address or landmark" icon={editing === "from" ? "circle-outline" : "map-marker"} placeholder={editing === "from" ? "Enter pickup location" : "Enter destination location"} value={customDraft[activePoint]?.detail ?? ""} onChangeText={(value) => updatePoint(activePoint, "detail", value)} /></BookingSection> : null}</BookingMapRouteShell>; }
