import { useState } from "react";
import { router } from "expo-router";
import { BookingScreen, BookingSection, FormField } from "@/components/booking/booking-ui";
import { RouteEntryCard } from "@/components/booking/route-entry-card";
import { isRouteComplete } from "@/lib/service-booking";
import { routeSuggestionToAddress } from "@/lib/route-autocomplete";
import { useBookingDraft } from "@/stores/booking-draft";

export default function CustomRouteScreen() { const { customDraft, updateCustomDraft } = useBookingDraft(); const [editing, setEditing] = useState<"from" | "to" | null>(null); const updatePoint = (target: "pickup" | "destination", field: "city" | "area" | "detail", value: string) => { const current = customDraft[target] ?? { city: "Lusaka", area: "", detail: "" }; updateCustomDraft({ [target]: { ...current, [field]: value } }); }; return <BookingScreen activeStep="route" serviceLabel="Custom Request" progressSteps={[{ id: "route", label: "Route" }, { id: "details", label: "Details" }, { id: "review", label: "Review" }]} title="Where should we move it?" detail="Search pickup and destination first. You can explain the special request next." continueLabel="Continue to details" continueDisabled={!isRouteComplete(customDraft.pickup, customDraft.destination)} onContinue={() => router.push("/custom/details" as never)}><RouteEntryCard scope="custom" from={{ value: customDraft.pickup?.detail ?? "", detail: customDraft.pickup?.area ?? "" }} to={{ value: customDraft.destination?.detail ?? "", detail: customDraft.destination?.area ?? "" }} onSuggestionSelect={(target, suggestion) => updateCustomDraft({ [target === "from" ? "pickup" : "destination"]: routeSuggestionToAddress(suggestion) })} onManualEntryPress={() => setEditing(editing ? null : "from")} accessibilityHint="Set the custom request pickup and destination" />{editing === "from" ? <BookingSection label="Manual pickup"><FormField label="Area" icon="map-marker-outline" placeholder="e.g. Longacres" value={customDraft.pickup?.area ?? ""} onChangeText={(value) => updatePoint("pickup", "area", value)} /><FormField label="Address or landmark" icon="circle-outline" placeholder="Enter pickup location" value={customDraft.pickup?.detail ?? ""} onChangeText={(value) => updatePoint("pickup", "detail", value)} /></BookingSection> : null}</BookingScreen>; }
