import { useState } from "react";
import { router } from "expo-router";
import { Text, View } from "react-native";

import { BookingQuickEditDrawer } from "@/components/booking/booking-quick-edit-drawer";
import { BookingScreen, SummaryRow } from "@/components/booking/booking-ui";
import { cargoItemsSummary } from "@/lib/booking-cargo";
import { intercityFulfilmentEditChoices } from "@/lib/booking-review-edits";
import { intercitySteps, isIntercityReady } from "@/lib/service-booking";
import { useSubmitBooking } from "@/lib/use-cases/use-submit-booking";
import { useBookingDraft } from "@/stores/booking-draft";

export default function IntercityReviewScreen() { const { intercityDraft, updateIntercityDraft } = useBookingDraft(); const submission = useSubmitBooking(); const [collectionEditOpen, setCollectionEditOpen] = useState(false); const submit = async () => { if (await submission.submit("intercity", intercityDraft)) router.replace("/intercity/confirmation" as never); }; return <BookingScreen activeStep="review" serviceLabel="City-to-City" progressSteps={intercitySteps} title="Review your Katundu" detail="We will confirm your available schedule and final quote before collection." continueLabel={submission.status === "submitting" ? "Submitting..." : "Request a quote"} continueDisabled={!isIntercityReady(intercityDraft) || submission.status === "submitting"} onContinue={submit}><View><SummaryRow label="Route" value={`${intercityDraft.originCity ?? "Origin"} → ${intercityDraft.destinationCity ?? "Destination"}`} /><SummaryRow label="Cargo" value={cargoItemsSummary(intercityDraft.cargoItems, intercityDraft.cargoDescription || intercityDraft.cargoCategory || "Not selected")} /><SummaryRow label="Photos" value={intercityDraft.cargoPhotos?.length ? `${intercityDraft.cargoPhotos.length} added` : "None"} /><SummaryRow label="Supporting document" value={intercityDraft.supportingDocument?.name ?? "Not attached"} /><SummaryRow label="Collection" value={intercityDraft.fulfilment === "door_delivery" ? "Door delivery" : "Collection point"} onEdit={() => setCollectionEditOpen(true)} /><SummaryRow label="Receiver" value={intercityDraft.receiver?.name ?? "Not provided"} /></View>{submission.errorMessage ? <Text style={{ color: "#B42318", fontSize: 12, fontWeight: "700" }}>{submission.errorMessage}</Text> : null}<BookingQuickEditDrawer<"collection" | "door_delivery"> visible={collectionEditOpen} overline="Collection" title="Change collection" detail="Update this preference without leaving your review." value={(intercityDraft.fulfilment ?? "collection") as "collection" | "door_delivery"} choices={intercityFulfilmentEditChoices} approveLabel="Update collection" onDismiss={() => setCollectionEditOpen(false)} onApprove={(fulfilment) => { updateIntercityDraft({ fulfilment }); setCollectionEditOpen(false); }} /></BookingScreen>; }
